language: android
jdk: oraclejdk8
before_install:
 - chmod +x gradlew
android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository